# Generated by Django 3.1.7 on 2021-04-06 03:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('postcode', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(default='AnonymousUser', max_length=200, null=True)),
                ('email', models.CharField(default='AnonymousUser', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=50, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size', models.DecimalField(decimal_places=1, max_digits=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('collection', models.CharField(max_length=50)),
                ('gender_category', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], max_length=20)),
                ('shoe_category', models.CharField(choices=[('E', 'Evening Wear'), ('S', 'Sport'), ('P', 'Pumps'), ('H', 'Highheels'), ('C', 'Casual'), ('SA', 'Sandals'), ('SL', 'Slippers')], max_length=20)),
                ('colour', models.CharField(default='Unregistered', max_length=30)),
                ('materials', models.CharField(default='Unregistered', max_length=50)),
                ('description', models.TextField(default='Unregistered', max_length=800)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('shoe_image', models.ImageField(default='DefaultEmptyImage.png', upload_to=mainapp.models.upload_media)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5)),
                ('sizes', models.ManyToManyField(help_text='Shoe Sizes of the product currently offered', to='mainapp.Size')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('rating', models.IntegerField(choices=[(5, '5'), (2, '2'), (3, '3'), (4, '4'), (1, '1')])),
                ('comment', models.TextField(max_length=500)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', related_query_name='shoe', to='mainapp.shoe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_users', related_query_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('size', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.order')),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.shoe')),
            ],
        ),
    ]
