# Generated by Django 3.1.7 on 2021-04-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210407_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gender_category',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_category',
            field=models.CharField(choices=[('SA', 'Sandals'), ('SL', 'Slippers'), ('C', 'Casual'), ('S', 'Sport'), ('P', 'Pumps'), ('E', 'Evening Wear'), ('H', 'Highheels')], max_length=20),
        ),
    ]
