# Generated by Django 3.1.7 on 2021-04-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210407_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='gender_category',
            field=models.CharField(choices=[('U', 'Unisex'), ('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_category',
            field=models.CharField(choices=[('SA', 'Sandals'), ('P', 'Pumps'), ('S', 'Sport'), ('SL', 'Slippers'), ('E', 'Evening Wear'), ('C', 'Casual'), ('H', 'Highheels')], max_length=20),
        ),
    ]
