# Generated by Django 3.1.7 on 2021-04-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210407_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='gender_category',
            field=models.CharField(choices=[('U', 'Unisex'), ('F', 'Female'), ('M', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_category',
            field=models.CharField(choices=[('P', 'Pumps'), ('S', 'Sport'), ('H', 'Highheels'), ('SL', 'Slippers'), ('SA', 'Sandals'), ('C', 'Casual'), ('E', 'Evening Wear')], max_length=20),
        ),
    ]
