# Generated by Django 3.1.7 on 2021-04-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210407_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='shie',
            new_name='shoe',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_category',
            field=models.CharField(choices=[('C', 'Casual'), ('SA', 'Sandals'), ('P', 'Pumps'), ('H', 'Highheels'), ('S', 'Sport'), ('SL', 'Slippers'), ('E', 'Evening Wear')], max_length=20),
        ),
    ]
